es:
  host: localhost
  password: 9YfcLUcxKiDvtzef1piK
  port: 9200
  user: elastic
llm:
  Spark_url: ws(s)://spark-api.xf-yun.com/v3.5/chat
  api_key: 3df6675e31e2480676984973fb4965db
  api_secret: ZTNkZjBkMmQwNzY0ZDVlNjkxZjBhNjY4
  appid: 508af837
  domain: generalV3.5
mysql:
  database: QADB
  host: localhost
  password: '123456'
  port: 3306
  user: root
recommendModel:
  base_path: ./RecommendModel/Models/
  model_id: 2
  model_name: modelv2
test: test1
